apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: argocd
spec:
  encryptedData:
    api-token: AgAjlLyLulAeRjJg3sPZUY+moe0EpZ9BCah00LFExzTyhycvPYMYfgsa49nWAzXpTiZxXQ+Kbk4V2/eOZZ3GDYNm60MyjKjC2AEIRMUcq/SyrUl5jAtqjgFHk5ZAzmJw8veT8eMhPV5FPAL8ZtsKLP2Eavdfn228zf7+gLDoOst9lPUMPJGsAnmas1Z8J26eCHn/+qkxPFHxxaivUnZ8my2pPsBT2z/AAwLF4yWd5OdPdYxXz5Zp8+feSHMNyRcigD71iMkzjecWx68ZfQrePyQXdiwSWPVNYpaHatfqRRQP5NxECRI9FXjK4iB0bBQM35IeQpAnMnJ++wFr8LLLZVtLPI/StLoQiDZOYSSkvZjAeo5YcKsDMG/2lbMYe1XIdkJS4JbQFk/JI3bbQbL2fa7B773ka6639p7hz7ennwGqEb6lVdeTaGXKQEtsZ8RTenIeR2fFRN43Ci+M6U+8uP/EZOby+H+bSKeXbyIBaXFUE38FVqwqCZtek94/VRbGVJu7CzqZ3PD44p47qkKFXrv7syQ7kq0QmauaCw4yXpOsYrczq4mDbzsyvYTYZ3FxTCL1988Kd0a8yYlytPp97aHq4VApJdrbnAD763dikBMocq6+HDHYCznLW2yjh9ah6Uer8FjNwRMTP8WhmDnMK+NMgmahmYwk6xCxEFuvuOyq2cZtpFTFIwIccFpqHGS37/tNByRCuu226R6AUYAMvwFlgrr3I9cK2ogg4DfD1KrV0DcX1yxAfnes
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: argocd
    type: Opaque

