apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: argocd
spec:
  encryptedData:
    api-token: AgAD5o0b/7dhKyiUIGULbO1XWDTh/GZQqTcy7tPY8qKkgjuOwWwlQPIulauzeEmYkvEUzy4mq20ZuksZLTXCc3D/ho7PdlFKAfpq7OCp/l8QQIgOofgINvOjmbSEo4hrqHrzAu1OUqoyHI7hDHltfOevhBWJphHW0+hfRBuGoeRSsC53ZboCRnj3O93zp8+apeH6JQS4A1zsma7fTxMmjwgW3yZxRNFXKZKBYdOdC8TiMqZJzmcqYdsCDAU4txYA+wdhMh0YEhngb8COVVkkFYuDEBxZzC/5zeg25Eju3wqPXfHBXiSGN8sb5ZxcwOLiWJpOflsWnuQwva0UNX7esAOT8c4EVrKMLsn/CTdV2aRuriVzowez2dWR4A2A/eYJjQvabqpn9LmyoaSEXIS+UQEJT1rnyAmCtS6dH6lPoAjCwIhYiGiRW23G9FJxlnESUdzvFvz4Uq6WsFa/rvWwJliMFOJLsankV1zrumYQ+AH9eetrD4egy+rjjxegiW/xM1DgBSaEztxlpatw9XeBH8Gm4xmeAPObCn60IRxILFFWARqXdtk2zGhkNJjBrLao6HJYZDteCNGAyk7ZpNuY68CRh5LMq6Yx8M5uBVMpT2dTYruMNsmM7ns8Iv3zIgw6UwJbOeU0Sh4yi3TA6722q37b3HAcuMRw7zpGgvDUgwNTfx8Egkh06Y/UkTdqg/98StQ6KvqYKpvGrt4iOvt6msBOKDn+DKpUFxUo5flYgMveA1xX6OBhLVnW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: argocd
    type: Opaque

