apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/cert-manager.yaml
- base/metal-lb.yaml
- base/ingress-nginx.yaml
- base/sealedsecrets.yaml
- base/argocd.yaml
namespace: argocd
