---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.0/manifests/install.yaml
  - base/argo-cd-ingress.yaml
  - base/argo-cd-issuer.yaml
  - base/cloudflare-api-token-sealed.yaml

