---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.2/manifests/install.yaml
  - base/argo-cd-ingress.yaml
  - base/argo-cd-issuer.yaml
  - base/cloudflare-api-token-sealed.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value: {"kubernetes.io/arch": "amd64"}
    target:
      group: apps
      version: v1
      kind: Deployment

  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value: {"kubernetes.io/arch": "amd64"}
    target:
      group: apps
      version: v1
      kind: StatefulSet
