apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.0.17
    chart: ingress-nginx
    helm:
      values: |-
        controller:
          extraArgs:
            enable-ssl-passthrough: true
          service:
            loadBalancerIP: 192.168.2.240      
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
