apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: MetalLb
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: MetalLb
    repoURL: https://github.com/34fathombelow/kube-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
